# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/icons8-resume-website-100.png

# Personal info
name: Kai Li
title: Bioinformatics Programmer
email: likaicnsh@gmail.com
phone: +1 571 250 9112
cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
twitter_username: KaiPeiLi
github_username:  KaiLiCn
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile_2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a bioinformatics programmer with four years experience in proteomics and proteogenomics area. In these years, I developed many proteomics tools and workflows with my collegues. For example, PDV, developed by our team, was recommended by the journal editor and college professor. 
  After work, I am a big fan of tennis.
  
    - [My CV](https://kailicn.github.io/kailicv/KaiLi_2020.pdf)

# Projects Section
projects_title: Publications #(Use this to override about projects section title)
# projects_content: |

# Experience Section
# experience_title: Work Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Skills:** Java, Linux, R, P ython, AWS
  
  **Conference:** Speaker on ASMS(American Society for Mass Spectrometry) 2020 Reboot
  
# More Section
more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Wang, X., Codreanu, S. G., Wen, B., Li, K., Chambers, M. C., Liebler, D. C., & Zhang, B. (2018). Detection of proteome diversity resulted from alternative splicing is limited by trypsin cleavage specificity. Molecular & Cellular Proteomics, 17(3), 422-430.
  Clark, D. J., Dhanasekaran, S. M., Petralia, F., Pan, J., Song, X., Hu, Y., ... & Ma, W. (2019). Integrated proteogenomic characterization of clear cell renal cell carcinoma. Cell, 179(4), 964-983.
  Li, K., Vaudel, M., Zhang, B., Ren, Y., & Wen, B. (2019). PDV: an integrative proteomics data viewer. Bioinformatics, 35(7), 1249-1251.
  Dou, Y., Kawaler, E. A., Zhou, D. C., Gritsenko, M. A., Huang, C., Blumenberg, L., ... & Liu, W. (2020). Proteogenomic characterization of endometrial carcinoma. Cell, 180(4), 729-748.
  Li, B., Li, N., Zhang, L., Li, K., Xie, Y., Xue, M., & Zheng, Z. (2018). Hsa_circ_0001859 regulates ATF2 expression by functioning as an MiR-204/211 sponge in human rheumatoid arthritis. Journal of immunology research, 2018.
  Ren, Z., Qi, D., Pugh, N., Li, K., Wen, B., Zhou, R., ... & Jones, A. R. (2019). Improvements to the rice genome annotation through large-scale analysis of RNA-Seq and proteomics data sets. Molecular & Cellular Proteomics, 18(1), 86-98.
  Gillette, M. A., Satpathy, S., Cao, S., Dhanasekaran, S. M., Vasaikar, S. V., Krug, K., ... & Krek, A. (2020). Proteogenomic characterization reveals therapeutic vulnerabilities in lung adenocarcinoma. Cell, 182(1), 200-225.
  Wen, B., Li, K., Zhang, Y., & Zhang, B. (2020). Cancer neoantigen prioritization through sensitive and reliable proteogenomics analysis. Nature communications, 11(1), 1-14.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
